// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {frontend} from '../models';

export function AddCategory(arg1:string):Promise<void>;

export function AddOrder(arg1:models.CheckoutOrderModel):Promise<string>;

export function AddRefundOrder(arg1:models.CheckoutOrderModel,arg2:number):Promise<string>;

export function CheckApiUrl(arg1:string):Promise<string>;

export function CheckBarcodeScanner():Promise<boolean>;

export function CheckForUpdate():Promise<services.UpdateInfo>;

export function CheckPrinterStatus(arg1:string):Promise<string>;

export function CleanupDuplicates():Promise<void>;

export function ClearAllData():Promise<void>;

export function ClearSyncLogs():Promise<void>;

export function CloseCustomerDisplay():Promise<void>;

export function CloseDrawer(arg1:number,arg2:number,arg3:number):Promise<void>;

export function CreateCustomerQuick(arg1:string,arg2:string):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteCustomer(arg1:number):Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function DeleteStaff(arg1:number):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<Record<string, string>>>;

export function GetAppMode():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetCategories():Promise<Array<models.ProductCategory>>;

export function GetCompanies():Promise<Array<Record<string, string>>>;

export function GetCurrentDrawer():Promise<models.CashDrawer>;

export function GetCustomerBalance(arg1:string):Promise<number>;

export function GetCustomers():Promise<Array<models.Customer>>;

export function GetCustomersMap():Promise<Array<Record<string, string>>>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetDatabaseStats():Promise<Record<string, any>>;

export function GetDeliveryOrders():Promise<models.OrderPosSearchResultModelOffline>;

export function GetDrawerStats(arg1:number):Promise<Record<string, any>>;

export function GetIsCustomerDisplay():Promise<boolean>;

export function GetModeOfPayments():Promise<Array<Record<string, string>>>;

export function GetNetworkPing():Promise<number>;

export function GetOrders(arg1:string,arg2:string,arg3:models.OrderFilteringModel):Promise<models.OrderPosSearchResultModelOffline>;

export function GetPosProfileDetails(arg1:string):Promise<Record<string, string>>;

export function GetPosProfiles():Promise<Array<string>>;

export function GetPriceLists():Promise<Array<string>>;

export function GetPrinters():Promise<Array<string>>;

export function GetProducts(arg1:string):Promise<Array<models.Product>>;

export function GetPromotions():Promise<Array<models.Promotion>>;

export function GetScreens():Promise<Array<frontend.Screen>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetStaffs():Promise<Array<models.Staff>>;

export function GetStockLevel(arg1:string):Promise<number>;

export function GetSyncLogs():Promise<Array<models.SyncLog>>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetUnsyncedOrderCount():Promise<number>;

export function GetWarehouses():Promise<Array<Record<string, string>>>;

export function Greet(arg1:string):Promise<string>;

export function HardReset():Promise<void>;

export function LoadProducts():Promise<Array<models.Product>>;

export function LogFrontend(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function ManualSyncOrder(arg1:string):Promise<void>;

export function OpenCashDrawer():Promise<void>;

export function OpenCustomerDisplay(arg1:number):Promise<void>;

export function OpenDrawer(arg1:number,arg2:number,arg3:string):Promise<void>;

export function PrintKitchenBill(arg1:models.CheckoutOrderModel):Promise<void>;

export function PrintPriceTag(arg1:models.Product):Promise<void>;

export function PrintSlip(arg1:models.CheckoutOrderModel):Promise<void>;

export function SaveCustomer(arg1:models.Customer):Promise<void>;

export function SaveProduct(arg1:models.Product):Promise<void>;

export function SavePromotion(arg1:models.Promotion):Promise<void>;

export function SaveSetting(arg1:string,arg2:string,arg3:number):Promise<void>;

export function SaveStaff(arg1:models.Staff):Promise<void>;

export function SelectAndSaveImage():Promise<string>;

export function SendReceipt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncAllData():Promise<void>;

export function SyncCustomersOnly():Promise<void>;

export function SyncProductsOnly():Promise<void>;

export function UpdateOrderMetadata(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function UpdateProductAvailability(arg1:string,arg2:boolean):Promise<void>;

export function ValidateCouponCode(arg1:string):Promise<Record<string, any>>;

export function ValidateGiftCard(arg1:string):Promise<Record<string, any>>;

export function ValidatePin(arg1:string):Promise<models.Staff>;
