// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function AddOrder(arg1) {
  return window['go']['main']['App']['AddOrder'](arg1);
}

export function AddRefundOrder(arg1, arg2) {
  return window['go']['main']['App']['AddRefundOrder'](arg1, arg2);
}

export function CheckApiUrl(arg1) {
  return window['go']['main']['App']['CheckApiUrl'](arg1);
}

export function CheckBarcodeScanner() {
  return window['go']['main']['App']['CheckBarcodeScanner']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckPrinterStatus(arg1) {
  return window['go']['main']['App']['CheckPrinterStatus'](arg1);
}

export function CleanupDuplicates() {
  return window['go']['main']['App']['CleanupDuplicates']();
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function ClearSyncLogs() {
  return window['go']['main']['App']['ClearSyncLogs']();
}

export function CloseCustomerDisplay() {
  return window['go']['main']['App']['CloseCustomerDisplay']();
}

export function CloseDrawer(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloseDrawer'](arg1, arg2, arg3);
}

export function CreateCustomerQuick(arg1, arg2) {
  return window['go']['main']['App']['CreateCustomerQuick'](arg1, arg2);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteProduct(arg1) {
  return window['go']['main']['App']['DeleteProduct'](arg1);
}

export function DeleteStaff(arg1) {
  return window['go']['main']['App']['DeleteStaff'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAppMode() {
  return window['go']['main']['App']['GetAppMode']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCompanies() {
  return window['go']['main']['App']['GetCompanies']();
}

export function GetCurrentDrawer() {
  return window['go']['main']['App']['GetCurrentDrawer']();
}

export function GetCustomerBalance(arg1) {
  return window['go']['main']['App']['GetCustomerBalance'](arg1);
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetCustomersMap() {
  return window['go']['main']['App']['GetCustomersMap']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetDatabaseStats() {
  return window['go']['main']['App']['GetDatabaseStats']();
}

export function GetDeliveryOrders() {
  return window['go']['main']['App']['GetDeliveryOrders']();
}

export function GetDrawerStats(arg1) {
  return window['go']['main']['App']['GetDrawerStats'](arg1);
}

export function GetIsCustomerDisplay() {
  return window['go']['main']['App']['GetIsCustomerDisplay']();
}

export function GetModeOfPayments() {
  return window['go']['main']['App']['GetModeOfPayments']();
}

export function GetNetworkPing() {
  return window['go']['main']['App']['GetNetworkPing']();
}

export function GetOrders(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetOrders'](arg1, arg2, arg3);
}

export function GetPosProfileDetails(arg1) {
  return window['go']['main']['App']['GetPosProfileDetails'](arg1);
}

export function GetPosProfiles() {
  return window['go']['main']['App']['GetPosProfiles']();
}

export function GetPriceLists() {
  return window['go']['main']['App']['GetPriceLists']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetProducts(arg1) {
  return window['go']['main']['App']['GetProducts'](arg1);
}

export function GetPromotions() {
  return window['go']['main']['App']['GetPromotions']();
}

export function GetScreens() {
  return window['go']['main']['App']['GetScreens']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetStaffs() {
  return window['go']['main']['App']['GetStaffs']();
}

export function GetStockLevel(arg1) {
  return window['go']['main']['App']['GetStockLevel'](arg1);
}

export function GetSyncLogs() {
  return window['go']['main']['App']['GetSyncLogs']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetUnsyncedOrderCount() {
  return window['go']['main']['App']['GetUnsyncedOrderCount']();
}

export function GetWarehouses() {
  return window['go']['main']['App']['GetWarehouses']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HardReset() {
  return window['go']['main']['App']['HardReset']();
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function LoadProducts() {
  return window['go']['main']['App']['LoadProducts']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function ManualSyncOrder(arg1) {
  return window['go']['main']['App']['ManualSyncOrder'](arg1);
}

export function OpenCashDrawer() {
  return window['go']['main']['App']['OpenCashDrawer']();
}

export function OpenCustomerDisplay(arg1) {
  return window['go']['main']['App']['OpenCustomerDisplay'](arg1);
}

export function OpenDrawer(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenDrawer'](arg1, arg2, arg3);
}

export function PrintKitchenBill(arg1) {
  return window['go']['main']['App']['PrintKitchenBill'](arg1);
}

export function PrintPriceTag(arg1) {
  return window['go']['main']['App']['PrintPriceTag'](arg1);
}

export function PrintSlip(arg1) {
  return window['go']['main']['App']['PrintSlip'](arg1);
}

export function SaveCustomer(arg1) {
  return window['go']['main']['App']['SaveCustomer'](arg1);
}

export function SaveProduct(arg1) {
  return window['go']['main']['App']['SaveProduct'](arg1);
}

export function SavePromotion(arg1) {
  return window['go']['main']['App']['SavePromotion'](arg1);
}

export function SaveSetting(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSetting'](arg1, arg2, arg3);
}

export function SaveStaff(arg1) {
  return window['go']['main']['App']['SaveStaff'](arg1);
}

export function SelectAndSaveImage() {
  return window['go']['main']['App']['SelectAndSaveImage']();
}

export function SendReceipt(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendReceipt'](arg1, arg2, arg3);
}

export function SyncAllData() {
  return window['go']['main']['App']['SyncAllData']();
}

export function SyncCustomersOnly() {
  return window['go']['main']['App']['SyncCustomersOnly']();
}

export function SyncProductsOnly() {
  return window['go']['main']['App']['SyncProductsOnly']();
}

export function UpdateOrderMetadata(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateOrderMetadata'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateProductAvailability(arg1, arg2) {
  return window['go']['main']['App']['UpdateProductAvailability'](arg1, arg2);
}

export function ValidateCouponCode(arg1) {
  return window['go']['main']['App']['ValidateCouponCode'](arg1);
}

export function ValidateGiftCard(arg1) {
  return window['go']['main']['App']['ValidateGiftCard'](arg1);
}

export function ValidatePin(arg1) {
  return window['go']['main']['App']['ValidatePin'](arg1);
}
